// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zahshpsekhsdcyuzjkxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaHNocHNla2hzZGN5dXpqa3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTY5NDksImV4cCI6MjA1NzYzMjk0OX0.hT66JvDphNt4BLp74-68p1kDmBnaMp3VLzFR9-3y9NA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);